### ISSUE TITLE
Refactor and improvements

### ISSUE THREAD

**Issue by phenax** [phenax/plasmajs#11]
Parts up for refactoring:
  - [ ] Replace [extended response](https://github.com/phenax/plasmajs/blob/master/app.jsx#L89) with a context object with untouched request and response and the helper methods on the context object.
  - [ ] Middleware should not have the terminate method. It should instead be with the context object and the `MiddleWare#onRequest` method execution and `isTerminalResponse` check happens in the Server class (previous point) #10
  - [ ] CLI improvements #9
  - [ ] De-JSX-ify the files #12 
  - [ ] Use Jest for testing #13 
  - [ ] Airbnb config #14

**Comment by jayands** [comment]
Also, may I suggest the following as well?
 - [ ] De-JSX-ify the files #12 
 - [ ] Use Jest for testing #13 
- [ ] Airbnb config #14
